### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#105]
Is there anything we can do so it's faster to render chunks?
https://prismarine.js.org/prismarine-viewer/standalone/
Things that can be improved:
* loading time: it takes about 30s to have the render being finished for the first time
* new rendering: when moving the view, it takes again about 30s to having the render being complete

This is a limitation in particular when trying to increase the view size to render many things.

What could be done to have this be done faster? (even if lowering the quality, that could be a setting)

**Comment by Karang** [comment]
the problem is mainly the generation:
* its filling air chunks
* its done in the main thread
It shouldn't be too hard to do better: https://github.com/PrismarineJS/prismarine-viewer/blob/master/examples/standalone/index.js#L33

**Comment by rom1504** [comment]
Yeah we can run the generator function in other threads in pworld.
Hopefully we can do something so it works both with browser and node
threads.

**Comment by rom1504** [comment]
now good enough by adding setTimeout so the main thread is not blocked
