### ISSUE TITLE
an example to generate a gif of the spawn zone automatically

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#11]
using https://github.com/puppeteer/puppeteer
https://threejs.org/examples/#webgl_worker_offscreencanvas

https://github.com/mrdoob/three.js/blob/19beb8ecc83b8f52de1e00dcfca59fc2ce55078f/test/e2e/puppeteer.js

**Comment by rom1504** [comment]
```
const puppeteer = require('puppeteer');
  
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://3000-e12d77a9-83d7-4acd-9b41-67e26a4ded5c.ws-eu01.gitpod.io/');
  await new Promise(resolve => setTimeout(resolve, 60000))
  await page.screenshot({path: 'example.png'});

  await browser.close();
})();
```
Produces

![image](https://user-images.githubusercontent.com/2346494/87260657-50ae1f00-c4b3-11ea-99ee-3e82656c5d3e.png)

**Comment by rom1504** [comment]
best way to auto zoom is probably to directly communicate with prismarine-viewer stuff

**Comment by Karang** [comment]
yeah the page can setup the camera easely. We can even compute the best camera position to fit the whole world.

**Comment by rom1504** [comment]
let's call this done

screencast would be even better but I looked and there's nothing easy
