### ISSUE TITLE
Electron crash on require

### ISSUE THREAD

**Issue by Mickman1** [PrismarineJS/prismarine-viewer#118]
I'm using Electron for my minecraft bot as the interface, hud, controls, etc. and I wanted to add the prismarine viewer in a frame inside the html. Whenever I import prismarine-viewer in plain nodejs everything works fine and a server starts running on my localhost, but in Electron, the moment I execute `const mineflayerViewer = require('prismarine-viewer').mineflayer`, Electron crashes and the DevTools disconnect.
I just want to put the viewer inside my Electron app. Any help / ideas? Thanks!

**Comment by Karang** [comment]
We have a dedicated example on how to run in electron: https://github.com/PrismarineJS/prismarine-viewer/tree/master/examples/electron

You can't use the mineflayer helper directly.
