### ISSUE TITLE
Electron app

### ISSUE THREAD

**Issue by Zn10plays** [PrismarineJS/prismarine-viewer#144]
Why not use electron + pviewer?

This is just a feature idea.

I think thet a desktop app would make dealing with pviewer easier.
It also leaves a lot of room for improvements and optimization, and new features.

**Comment by Karang** [comment]
You mean like https://github.com/PrismarineJS/prismarine-viewer/tree/master/examples/electron ?

**Comment by Zn10plays** [comment]
yes.
