### ISSUE TITLE
Grass color is wrong on borders of biomes

### ISSUE THREAD

**Issue by Xandertron** [PrismarineJS/prismarine-viewer#171]
not sure how this even happens, doesn't appear to be on any particular axis, and breaking blocks around it doesn't change it

![2021-03-21_19-24](https://user-images.githubusercontent.com/66480163/111926891-a7c1b600-8a7c-11eb-9514-fa16b70d515a.png)
![2021-03-21_19-23](https://user-images.githubusercontent.com/66480163/111926893-a85a4c80-8a7c-11eb-9f3a-bc221ed2f274.png)

**Comment by Karang** [comment]
Fixed, thanks.
