### ISSUE TITLE
Invisible world in 1.19.1 as well as latest

### ISSUE THREAD

**Issue by 3top1a** [PrismarineJS/prismarine-viewer#175]
![Screenshot_2021-03-27_21-35-04](https://user-images.githubusercontent.com/57371001/112735521-86f9d480-8f44-11eb-9a47-e1dfde43cfd5.png)

The world is missing, but click to move still works, so the world is just not rendering.

**Comment by 3top1a** [comment]
I also tried this in not-so-extention-heavy Brave, but the same issue still persisted.

**Comment by rom1504** [comment]
What is 1.19.1 ?

**Comment by 3top1a** [comment]
The viewer version

**Comment by rom1504** [comment]
What code are you running?
Any error in dev console?

**Comment by 3top1a** [comment]
I tried both the latest commit ([fb7b9d3](https://github.com/PrismarineJS/prismarine-viewer/commit/fb7b9d37804a5cf0e2dd5f53ed476a40bef37bc4)) and [1.19.1](https://github.com/PrismarineJS/prismarine-viewer/releases/tag/1.19.1).

Both had an empty world

**Comment by rom1504** [comment]
What code are you running?
Any error in chrome dev console?

**Comment by 3top1a** [comment]
I get one error: 

> TypeError: can't convert undefined to object

**Comment by rom1504** [comment]
What's the full error ?
What code are you running?

**Comment by 3top1a** [comment]
1.19.1,
![image](https://user-images.githubusercontent.com/57371001/112750091-f3f98280-8fb5-11eb-8646-677bc0003212.png)

**Comment by rom1504** [comment]
1.19.1 is the version of prismarine-viewer it's not the code you ran.
What code did you run?
Until you give more information it's going to be hard to help you

**Comment by 3top1a** [comment]
The click to move example, modified a bit:
```
const mineflayer = require('mineflayer');
const mineflayerViewer = require('prismarine-viewer').mineflayer

const { pathfinder, Movements } = require('mineflayer-pathfinder')
const { GoalBlock } = require('mineflayer-pathfinder').goals

username = null;
password = null;
server_ip = null;
port = null;
bot = null;

exports.connect = function() {
  console.log("teet");
  bot = mineflayer.createBot({
    host: server_ip,
    port: port,
    username: username,
    password: password,
    version: "1.12.2"
  });
}

exports.viewer = function(){
  bot.loadPlugin(pathfinder)
  mineflayerViewer(bot, { port: 3001 })

  bot.on('path_update', (r) => {
    const nodesPerTick = (r.visitedNodes * 50 / r.time).toFixed(2)
    console.log(`I can get there in ${r.path.length} moves. Computation took ${r.time.toFixed(2)} ms (${nodesPerTick} nodes/tick). ${r.status}`)
    const path = [bot.entity.position.offset(0, 0.5, 0)]
    for (const node of r.path) {
      path.push({ x: node.x, y: node.y + 0.5, z: node.z })
    }
    bot.viewer.drawLine('path', path, 0xff00ff)
  })

  const mcData = require('minecraft-data')(bot.version)
  const defaultMove = new Movements(bot, mcData)

  bot.viewer.on('blockClicked', (block, face, button) => {
    if (button !== 2) return // only right click

    const p = block.position.offset(0, 1, 0)

    bot.pathfinder.setMovements(defaultMove)
    bot.pathfinder.setGoal(new GoalBlock(p.x, p.y, p.z))
  })
}                                                                                                                                                      
 ```

**Comment by 3top1a** [comment]
![image](https://user-images.githubusercontent.com/57371001/112952616-3513a300-912c-11eb-8d98-4248bcb09e74.png)
There's something wrong with the tints, I'll check

**Comment by 3top1a** [comment]
I just installed the latest updates and it worked
