### ISSUE TITLE
Nicknames?

### ISSUE THREAD

**Issue by Timtaran** [PrismarineJS/prismarine-viewer#212]
![image](https://user-images.githubusercontent.com/60805088/128586104-9c542f37-170b-4da6-85da-ebc4975846d9.png)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-viewer/blob/6d527e3d6d6646acfa6c79fc7fa9e2afadb98cf8/viewer/lib/entities.js#L11

what entity is it ?

**Comment by Timtaran** [comment]
Player

**Comment by Karang** [comment]
You are using an outdated version, please update.
