### ISSUE TITLE
Displaying blocks + more players

### ISSUE THREAD

**Issue by ImMaxUK** [PrismarineJS/prismarine-viewer#214]
Hello,

I had a go at displaying about 30 ish players but I had no luck (looked like attached image), is this meant for smaller amounts? 

![image](https://user-images.githubusercontent.com/70581172/130696773-1bee0a86-751d-475d-a063-d21bcbc9bf36.png)

**Comment by AwesomestCode** [comment]
Looks fine to me? I don't see what's wrong.

**Comment by ItzMonkeyMax** [comment]
Yeah, it's a bit of an odd one.

Doesn't seem to load, after waiting about 5 minutes. It just has entities + players right now.

**Comment by Karang** [comment]
Seems like you have too many entities. Entity rendering isn't as optimized as block rendering, it seems to be eating all the computing budget.
