### ISSUE TITLE
somehow listen to an "all rendered" event in the tests

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#22]
either from the browser or the server

**Comment by Karang** [comment]
With one subtility: at each block updates, the sections gets re-rendered (for instance when a dirt turn into grass).
The "all rendered" could be a "initial render done" or something like that

**Comment by Karang** [comment]
In the new version, the rendering order is in a spiral arround the player chunk, so it guarantees that even if the rendering isnt finished there will be something on the screenshot. Is the event still needed ?

**Comment by rom1504** [comment]
no
