### ISSUE TITLE
Unable to create mineflayer viewer with special arguments in Python

### ISSUE THREAD

**Issue by SpacePython12** [PrismarineJS/prismarine-viewer#233]
When I try to initialize the mineflayer viewer through Python, it requires two arguments, the bot and the options. Since Python doesn't have a "primitive value type" (idk, I'm new to this), the class is returned as null. 
(Of course I used `Viewer = require("prismarine-viewer").mineflayer`.)
I tried `self.viewer = Viewer(self.bot, firstPerson=True)`,
and `self.viewer = Viewer(self.bot, {firstPerson: True})`,
and also `self.viewer = Viewer(self.bot, "{ firstPerson: true }")`

Am I missing something?

**Comment by extremeheat** [comment]
in python, dictionary keys must be put in quotation marks,
```py
self.viewer = Viewer(self.bot, { 'firstPerson': True })
```

an example with mineflayer:

![image](https://user-images.githubusercontent.com/13713600/146343641-9fdd0bad-4ea0-4d35-aabc-f58d359ac77c.png)

**Comment by SpacePython12** [comment]
Awesome, thanks for the help!
