### ISSUE TITLE
It doesnt seem to work, whenever i start it

### ISSUE THREAD

**Issue by SebastianMostert** [PrismarineJS/prismarine-viewer#237]
index.js:2 THREE.WebGLRenderer: Error creating WebGL context.
Qs @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
index.js:2 Uncaught Error: Error creating WebGL context.
    at new Qs (index.js:2)
    at index.js:2
    at index.js:2
    at index.js:2

**Comment by rom1504** [comment]
provide more info on your env
likely you don't have a X server
