### ISSUE TITLE
Render water/lava

### ISSUE THREAD

**Issue by Karang** [PrismarineJS/prismarine-viewer#24]
Water and lava don't have a model described in json. This should be handled specially.

**Comment by Karang** [comment]
I added a basic implementation. This are the missing things:
* correctly handle waterlogged blocks (waterlogged property + seagrass (which doesn't have waterlogged property))
* fix z-order of water to avoid transparency glitchs (the only way is to have all water in a separate mesh and to render it after all opaques blocks)
* render correctly the flowing water

**Comment by TreeOfSelf** [comment]
Hi! I would love to have access to your basic implementation if possible.

**Comment by Karang** [comment]
You have https://github.com/PrismarineJS/prismarine-viewer/blob/master/src/models.js#L72

**Comment by TreeOfSelf** [comment]
Sweet, thank you tons.
