### ISSUE TITLE
Support 1.18

### ISSUE THREAD

**Issue by ZockerBoysHD** [PrismarineJS/prismarine-viewer#240]
hi theere,e
after inteegrating this into my bot, and visiing the webpag, i only see mobs and players but no blocks.
i get this mass spam of errors in my browser console (tested chrome)
![image](https://user-images.githubusercontent.com/30929430/150690714-c1faf8ea-90e9-42a0-9fe9-b6b05ac75be5.png)

using mc 1.18.1 and latest repo / module versions available using npm i

**Comment by extremeheat** [comment]
1.18 is not currently supported

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-viewer/pull/241 put instructions on what to do there if you want it

**Comment by rom1504** [comment]
done
