### ISSUE TITLE
Correct tint for blocks

### ISSUE THREAD

**Issue by Karang** [PrismarineJS/prismarine-viewer#25]
Block tint depends on the type of block and for some blocks on the biome.
The correct colors for each combinations are listed here:
https://minecraft.gamepedia.com/Tint

Tint is currently hardcoded to plain grass green for blocks:
https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/models.js#L232

And to ocean blue for water:
https://github.com/PrismarineJS/prismarine-viewer/blob/master/viewer/lib/models.js#L106

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-wiki-extractor might be useful for any contributor interested on this

**Comment by Karang** [comment]
Done
