### ISSUE TITLE
Produce screencast automatically

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#26]
First step is more googling / reading https://github.com/puppeteer/puppeteer/issues/478

Then we can use that in the tests
Might also be interesting as an example (without adding the dependency to puppeteer obviously)

An use case could be to automatically follow the bot from above, for example to capture the movements of a Pathfinding bot

**Comment by Karang** [comment]
We could also add an optional delay between frames and have a timelapse tool :)

**Comment by rom1504** [comment]
https://github.com/muralikg/puppetcam seems promising

**Comment by Karang** [comment]
We can do screencast with the headless renderer now.

**Comment by rom1504** [comment]
Yes indeed, I'll try it out

**Comment by rom1504** [comment]
this is done
