### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by Stuntlover-TM** [PrismarineJS/prismarine-viewer#321]
Prismarine viewer not rendering correctly in 1.19, example: https://cdn.discordapp.com/attachments/947894924496482354/1039960731208138752/image.png

**Comment by wntiv-main** [comment]
I am having the same issue on a 1.16.5 server

**Comment by Choneas** [comment]
yes I have this error too!

**Comment by Densyakun** [comment]
Currently, prismarine-viewer and dependent libraries are not compatible with version 1.19.

**Comment by LolekLiam** [comment]
set your bots version to 1.18.2 and install viaversion to your server

**Comment by Stuntlover-TM** [comment]
> set your bots version to 1.18.2 and install viaversion to your server

I doubt most people are using bots on their own server xdd

**Comment by rom1504** [comment]
it's not supported, that's why. Please bring support

**Comment by rom1504** [comment]
start with #286

**Comment by OrilinZ** [comment]
Error: Unknown entity glow_squid

**Comment by rom1504** [comment]
So mc assets has 1.19 now, this needs to be tested and done

**Comment by rom1504** [comment]
done
