### ISSUE TITLE
RENDER NOT WORKING!!!

### ISSUE THREAD

**Issue by Choneas** [PrismarineJS/prismarine-viewer#330]
It just like this.
We just can see the entities and the dropped-item is purple.
https://github.com/PrismarineJS/prismarine-viewer/issues/321
this is my shoot.
![image](https://user-images.githubusercontent.com/57039359/206971928-efa5f5f4-e67c-4d94-96a7-dfff54ed3a9d.png)

**Comment by david1384** [comment]
Try to set the bot version in "const bot" to the server version.
ex:      
const bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : 'viewer',
  password: process.argv[5]
  version: process.argv[5]
})

**Comment by david1384** [comment]
Is the server you are trying to connect to using viaversion? Because it creates a problem with prismarine-viewer.

**Comment by arajooj** [comment]
The same is happening to me
![image](https://user-images.githubusercontent.com/37886774/210123181-f4310a02-4c5d-4519-b912-4d542630a25f.png)

I`am use ViaVersion and ViaBackwards.

**Comment by zardoy** [comment]
all this because because either textures or block states didn't load, a loading indicator or error indicator should be added in the UI!
