### ISSUE TITLE
World not showing

### ISSUE THREAD

**Issue by Kalmai221** [PrismarineJS/prismarine-viewer#356]
I used all of the example code but all I can see is the bot, not the world
![Screenshot_2023-02-20-13-27-15-97_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/67641154/220121683-1f36531b-2931-41dd-bc98-267fa4d4c8d9.jpg)

I have tested it on multiple browsers

**Comment by lpuv** [comment]
Same problem, any fix?

**Comment by extremeheat** [comment]
Up to 1.17 is supported

**Comment by Kalmai221** [comment]
Oh, ok
