### ISSUE TITLE
Anyway to get the third person camera to follow the player?

### ISSUE THREAD

**Issue by TreeOfSelf** [PrismarineJS/prismarine-viewer#36]
Hi, I was hoping someone could give me the basic layout on how I would implement having the camera's X,Y,Z alter with the players.

**Comment by Karang** [comment]
Look here: https://github.com/PrismarineJS/prismarine-viewer/blob/master/src/index.js#L62
it was the case before but was removed because it prevented to move the camera freely with the mouse which was anoying

**Comment by TreeOfSelf** [comment]
Perfect, thank you.
