### ISSUE TITLE
Is there a way to control the bot movement? (First Person Mode)

### ISSUE THREAD

**Issue by Nurutomo** [PrismarineJS/prismarine-viewer#40]
`WASD` for `x` and `z` movement
`Spacebar` for `+y` movement or Fly Up
`Shift` for `-y` movement or Fly Down
`Mouse` for Camera Orbit

If this is not used in First Person, use this as camera movement

**Comment by Karang** [comment]
You can look at https://github.com/PrismarineJS/prismarine-viewer/tree/master/examples/python for an example.
