### ISSUE TITLE
Close headless socket connection

### ISSUE THREAD

**Issue by rogermiranda1000** [PrismarineJS/prismarine-viewer#401]
In #141 there was implemented a way to close the server ([ref](https://github.com/PrismarineJS/prismarine-viewer/blob/438264a1bc5a72ee9eb87153b95ed5326aeaf8f3/lib/mineflayer.js#L86)), but this is not available on the headless mode while using sockets. The connection gets created [here](https://github.com/PrismarineJS/prismarine-viewer/blob/438264a1bc5a72ee9eb87153b95ed5326aeaf8f3/lib/headless.js#L44), and cannot be destroyed.

**Comment by rom1504** [comment]
what is the question here?

**Comment by rogermiranda1000** [comment]
> what is the question here?

How do I destroy the socket (in headless mode)

**Comment by rom1504** [comment]
client is returned by the function creating the headless mode so you should be able to call .end() on it https://nodejs.org/api/net.html#socketenddata-encoding-callback
