### ISSUE TITLE
Only monsters visible

### ISSUE THREAD

**Issue by jimmy927** [PrismarineJS/prismarine-viewer#407]
I can only see monsters, no blocks seem to be visible.
I this a known issue ?

![image](https://github.com/PrismarineJS/prismarine-viewer/assets/3243901/4c1e5ba8-dc5d-49b0-bb4b-1b2f0244ea85)

Running on windows.

```
PS C:\Users\jimmy\PycharmProjects\mineflayer> npm list                                                                                  
mineflayer@1.0.0 C:\Users\jimmy\PycharmProjects\mineflayer
+-- mineflayer-pathfinder@2.4.4
+-- mineflayer-pvp@1.3.2
+-- mineflayer@4.13.0
`-- prismarine-viewer@1.25.0
```

**Comment by rom1504** [comment]
Are you using a supported Minecraft version?
