### ISSUE TITLE
not load maps

### ISSUE THREAD

**Issue by lusento** [PrismarineJS/prismarine-viewer#430]
![image](https://github.com/PrismarineJS/prismarine-viewer/assets/149605553/01eabf6a-35da-429b-be1d-c6788ee41ad1)
![image](https://github.com/PrismarineJS/prismarine-viewer/assets/149605553/27846d07-14be-4869-9272-c3775fe7157b)
prismarine-viewer does not download maps from both the 3rd and 1st person, which are installed in front of the bot, one large map consisting of 6 small ones, a captcha on it, is there any way to make this captcha visible?

**Comment by greenik228** [comment]
you won't be able to get the image via prismarine-viewer. use [mineflayer-item-map-downloader](https://github.com/IceTank/mineflayer-item-map-downloader) instead, but the captcha in this case will be broken into 6 parts and most of them will be turned the wrong way
