### ISSUE TITLE
Please add a way to stop the viewer entirely. Right now there is no way to easily stop all the servers it runs so you are forced to restart the program

### ISSUE THREAD

**Issue by TreeOfSelf** [PrismarineJS/prismarine-viewer#46]

**Comment by TreeOfSelf** [comment]
Found a solution at least for my use case, I was having a bot that would be in a server that would be reset, then it would have to spawn a new bot in order to reconnect. SO I made the viewer return a function that allows you to attach a new bot to the viewer.

**Comment by rom1504** [comment]
Can you pr it ?

**Comment by TreeOfSelf** [comment]
Sure let me just find a neat way of doing it.
