### ISSUE TITLE
Loading Worker error

### ISSUE THREAD

**Issue by ratuspro** [PrismarineJS/prismarine-viewer#63]
I'm experiencing some problems when opening the viewer in Firefox.

The error is as follows:
`Loading Worker from “http://localhost:3001/node_modules/prismarine-viewer/src/worker.js” was blocked because of a disallowed MIME type (“text/html”)`

It also happens in other browsers such as Chrome and Edge.

It is possible to see the Firefox's logs in the following image
![unknown](https://user-images.githubusercontent.com/5813765/101046393-eb012300-3578-11eb-84ee-d2a8f7c92639.png)

The problem is related with the worker.js file being loaded from the wrong path.

**Comment by Karang** [comment]
Interesting, this was introduced in the latest version. Apparently the browser detection is failing. I'll see if I can reproduce, in the mean time you can revert back to pviewer 1.16.0.

Thanks for the reporting
