### ISSUE TITLE
Implement wasd controls in standalone

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-viewer#96]
related https://github.com/extremeheat/mceditor.js/blob/115f71ae103d1fe959cc296b2ef4a888439f59f8/src/viewer/custom/controls.js

**Comment by Karang** [comment]
Could be useful to test and debug prismarine-physics

**Comment by extremeheat** [comment]
#101 should implement WASD/ZQSD controls for third person mode. Doing first person controls would need to be linked to prismarine-physics, I'll look into it.

**Comment by rom1504** [comment]
done but indeed doing an example using this inside pphysics would be cool
