### ISSUE TITLE
How to localy test this package?

### ISSUE THREAD

**Issue by 3top1a** [PrismarineJS/prismarine-viewer#99]
I wanted to do #57, but I don't know how to test/run the package localy.
Any help?

**Comment by rom1504** [comment]
You can start any of the example with node

**Comment by 3top1a** [comment]
My changes are still not visible, i tried removing the players color in entities.js, I can still se it in red

**Comment by rom1504** [comment]
Run webpack again or use webpack serve

**Comment by 3top1a** [comment]
How?
(Sorry for my inexperience)

**Comment by rom1504** [comment]
node_modules/.bin/webpack

**Comment by 3top1a** [comment]
Still nothing

**Comment by rom1504** [comment]
What are you running ?

**Comment by 3top1a** [comment]
examples/bot.js

**Comment by rom1504** [comment]
What happened after you re-ran webpack ? Did it regenerate the public/ dir ?

**Comment by 3top1a** [comment]
There is a public/
Log:
```
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/not-a-weeb/Documents/mineflayer/prismarine-viewer
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: asset ./index.js 1.98 MiB [emitted] (name: main)
runtime modules 1010 bytes 5 modules
modules by path ./node_modules/ 1.74 MiB 60 modules
modules by path ./viewer/ 16.9 KiB
  ./viewer/index.js 186 bytes [built] [code generated]
  ./viewer/lib/viewer.js 2.59 KiB [built] [code generated]
  ./viewer/lib/worldView.js 4.18 KiB [built] [code generated]
  ./viewer/lib/simpleUtils.js 1.21 KiB [built] [code generated]
  ./viewer/lib/worldrenderer.js 4.47 KiB [built] [code generated]
  ./viewer/lib/entities.js 1.35 KiB [built] [code generated]
  ./viewer/lib/primitives.js 1.25 KiB [built] [code generated]
  ./viewer/lib/version.js 714 bytes [built] [code generated]
  ./viewer/lib/utils.electron.js 512 bytes [built] [code generated]
  ./viewer/lib/utils.js 512 bytes [built] [code generated]
./lib/index.js 1.86 KiB [built] [code generated]
./public/supportedVersions.json 100 bytes [built] [code generated]
webpack 5.11.0 compiled successfully in 3755 ms

asset ./worker.js 16 MiB [emitted] (name: main)
416 modules
webpack 5.11.0 compiled successfully in 5903 ms
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by rom1504** [comment]
Ok what do you run next ? Are you sure your change is doing something ?

**Comment by 3top1a** [comment]
node examples/bot.js

Yes, i made the character box have a green color.
It still has red

**Comment by rom1504** [comment]
It's not magical. Either you didn't change the code enough, either
something was not refreshed. Could be webpack, could be you didn't restart
the example, could be you didn't refresh in the browser,... Hard to tell
from here

**Comment by Karang** [comment]
How did you change it ?

**Comment by 3top1a** [comment]
Just give me a list of commands to build and test the package, I'll just copy the files

**Comment by rom1504** [comment]
I've already gave them above
1. node_module/.bin/webpack
2. node examples/bot.js

**Comment by 3top1a** [comment]
For anyone else (me included), just list the steps necesary to extend this module

**Comment by rom1504** [comment]
Yes. What are you confused about what I just said ?
Maybe you could come to our discord, I guess it would be easier to communicate there.

**Comment by 3top1a** [comment]
By the fact it still doesn't work

**Comment by extremeheat** [comment]
What doesn’t work? What’s the error? What happens? What have you tried? Can’t help you if you’re not more specific.

**Comment by 3top1a** [comment]
I have made a change in the entity.js file, making the player character green.
No matter what i tried, it's still red.

What I tried:
- npm link
- yarn add
- everything in the thread

**Comment by extremeheat** [comment]
Can you join the discord? It may be easier to help there. What changes did you make?

**Comment by 3top1a** [comment]
What room?

**Comment by Karang** [comment]
If you want to change the bot color you need to edit https://github.com/PrismarineJS/prismarine-viewer/blob/master/lib/index.js#L61

The code in entities.js is for other players. Ultimately this would need to be refactored to share some code.
